### ISSUE TITLE
推荐个文件分享软件

### ISSUE THREAD

**Issue by NextOmega** [xlucn/oh-my-foss-android#20]
https://gitlab.com/ivgeek/mixfile
简洁易用,非常流畅,不需要登录注册就可上传分享文件,上传下载不限速,上百G的大文件都可以上传
且文件是客户端加密解密的,服务端没办法得知文件内容,加密的视频直接能在线播放

**Comment by xlucn** [comment]
谢谢推荐，但是

**第一眼**

我没有很看明白这个项目README和Wiki里的介绍。上传到哪里？是
- 仅限局域网互传？（根据Wiki，好像是这个）
- self-hosted服务器？
- 开发者自己搭建了服务器？
- 使用了第三方服务器？

给谁传？什么定位？
- 我打开软件，别人给我快传文件？
- 我搭一个服务器，作为局域网云盘？
- 还是搭服务器，但作为影视库？
- 在安卓手机上，软件是服务端，还是客户端？

**第二眼**

Wiki提到了（以下信息信息都不容易看到）

> MixFile启动时会自动运行文件服务器

让人以为是运行此软件的设备作为服务器，存放文件。但又提到

> 文件使用了免费的第三方服务进行储存

这说明上传并非限于局域网，还是要连接外部网络，并且是不一定稳定、未向用户明确的第三方平台。这个就是很扣分的，绝对不能安心使用，没准什么时候就不能用，或者限速、网速不够而体验糟糕

我现在的判断是，这个软件暂时
1. 没有**给一般用户**很好的解释和对自己的定位。可能开发者们很熟悉这种概念，但会让路人非常迷惑。
2. 使用了不明确的第三方服务存储文件，虽然加密保证了安全性，但无法保证服务的长期稳定。不适于大面积推广

这个状况没有改变之前，暂时不考虑加入
