### ISSUE TITLE
cellular-z 也还不错

### ISSUE THREAD

**Issue by reatang** [xlucn/oh-my-foss-android#6]

**Comment by xlucn** [comment]
![Screenshot_20240129-220931_酷安.png](https://github.com/xlucn/oh-my-foss-android/assets/12032219/95c94bd7-1493-4091-af32-11d6c0e39abe)

这个吗，但是不是开源的

**Comment by xlucn** [comment]
先关掉了。如果不是我找到的这个，可以回复一下网址
